### ISSUE TITLE
Weird results?

### ISSUE THREAD

**Issue by Mordokkai** [seanbenhur/siamese_net#2]
Hi,

Thanks a lot for your code, that's interesting. I have a question regarding the results you showed on the front page of your git project. It seems that there is no threshold that can be used to separate the forged and the original signatures: distances for forged (0.5 and 1.10), distances for original (1.09 and 0.67). It seems strange to me, is it normal ?
Bests,

**Comment by seanbenhur** [comment]
Yes, the euclidean distance refers to how dissimilar both the images are, the issue here is, I need to train this model with much larger dataset to make it work well, so the predictions are wrong in some cases. And its been almost 1.5 years since I have worked on this project, so I don't really have time to improve this project currently. 


You can refer here for more on setting threshold: 
https://github.com/harveyslash/Facial-Similarity-with-Siamese-Networks-in-Pytorch/issues/42#issuecomment-918025157

**Comment by Mordokkai** [comment]
Ok thx for your answer! I was just wondering whether I didn't understand the model correctly. so in the end the model is ok, just need more training/data. I get it, thx!

**Comment by seanbenhur** [comment]
If you find any larger data other than this, feel free to share here, I may
try to spend some time on this project and improve the results.

Thanks
Sean
